# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Shelfie' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Shelfie
  pod 'google-cast-sdk'


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'ShelfieTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
